project:
  type: book
  output-dir: ../docs


book:
  title: "Sequential Transport for Causal Mediation Analysis"
  date: "02/09/2026"
  chapters:
    - index.qmd
    - part: I. Introduction
      chapters:
        - reminders.qmd
        - utils.qmd
        - functions.qmd
    - part: II. A Gaussian Example
      chapters:
        - gaussian-example.qmd
        - gaussian-example-mc.qmd
    - part: III. Counterfactuals for Categorical Data
      chapters:
        - transp-categ-objectives.qmd
        - transp-categ-coupling.qmd
        - transp-categ-discrete.qmd
        - transp-categ-transport.qmd
        - transp-categ-small-example.qmd
    - part: IV. Transport with Weights
      chapters:
        - transport-gaussian-local-weights.qmd
    - part: V. Experiments
      chapters:
        - xp-simulated.qmd
        - xp-compas.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/fer-agathe/causal_OT
        aria-label: GitHub


bibliography: ./references.bib


fig-cap-location: top


format:
  html:
    theme:
      light: [litera, styles-light.scss]
      dark: [darkly, styles-dark.scss]
    html-math-method: mathjax
    include-in-header:
    - file: mathjax-color.html
    - text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

filters:
  - pseudocode
  - diagram

diagram:
  directory: figs/diagrams
  format: svg
  tikz:
    engine: pdflatex

editor: source
